providers = ["nodejs"]

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-22_x", "npm"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["echo 'Build will be handled by start script'"]

[start]
cmd = "chmod +x start.sh && ./start.sh"